language: python
sudo: false
python:
  - "3.5"
  - "3.6"
# command to install dependencies
services:
  - postgresql
install:
  - "pip install -r requirements.txt"
# command to run tests
before_script:
  - createuser -l blog
  - createdb test_blog -O blog
script:
  - make test-db
  - make test
